### ISSUE TITLE
Require load error on Mac OS X

### ISSUE THREAD

**Issue by tsikov** [leishman/kraken_ruby#19]
After installing the gem and trying to load it with `require 'kraken_ruby'` I get the following error:

```
/Users/blabla/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- kraken_ruby (LoadError)
    from /Users/blabla/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from test.rb:1:in `<main>'
```

It seems that all dependancies are installed inside the installation directory, however the folder of the gem itself is completely empty. I just copied the contents of this repo there and it worked.

**Comment by ghost** [comment]
The same thing happens on GNU/Linux. @tsikov's suggestion of moving this repo's contents to the gem's folder fixes it!

**Comment by tostr7191** [comment]
I have the same problem. If you clone the repo and do

```
rake build
rake install
```

it installs and works. I assume it's the gem on rubygems that's broken?

**Comment by dukedorje** [comment]
Did a `bundle open kraken_ruby`.  The gem directory is empty!  Did someone delete the gem from rubygems, or forget to push the code?
